version: "3.5"

networks:
  frontend:
    external:
      name: proxy
  backend:
    driver: bridge
  db1:
    external:
      name: db1

services:
  httpd:
    container_name: app1
    build:
      context: ../../containers/httpd
    environment:
      VIRTUAL_HOST: app1.localhost
      CERT_NAME: localhost
    volumes:
      - ${DOCMENT_ROOT}:/usr/local/apache2/htdocs
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

  php-fpm:
    build:
      context: ../../containers/php-fpm/7.0
    volumes:
      - ${DOCMENT_ROOT}:/usr/local/apache2/htdocs
      - /var/run/docker.sock:/var/lib/mysql/mysql.sock:ro
    networks:
      - backend
      - db1

  composer:
    image: composer
    command: install
    volumes:
      - ${HOST_APP_PATH}:/app
